fn main() {
    tauri_build::build();

    // Enabling Tauri's `test` feature links native-dialog on Windows. Its test
    // executables import TaskDialogIndirect, which only exists in Common
    // Controls v6. Cargo test binaries do not inherit the application manifest
    // generated by tauri-build, so explicitly activate v6 for Windows link
    // targets. Checking Cargo's target OS keeps this MSVC-only argument out of
    // Android cross-compilation performed on a Windows host.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!(
            "cargo::rustc-link-arg=/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'"
        );
    }
}
