//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "attachment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
    pub sync_status: String,
    pub sync_version: i64,
    pub mime_type: String,
    #[sea_orm(column_type = "Blob")]
    pub data: Vec<u8>,
    pub sha256: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::question_attachment_cross_ref::Entity")]
    QuestionAttachmentCrossRef,
}

impl Related<super::question_attachment_cross_ref::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionAttachmentCrossRef.def()
    }
}

impl Related<super::question::Entity> for Entity {
    fn to() -> RelationDef {
        super::question_attachment_cross_ref::Relation::Question.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::question_attachment_cross_ref::Relation::Attachment
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
