//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

#![allow(unused_imports)]

pub use super::attachment::Entity as Attachment;
pub use super::question::Entity as Question;
pub use super::question_attachment_cross_ref::Entity as QuestionAttachmentCrossRef;
pub use super::question_tag_cross_ref::Entity as QuestionTagCrossRef;
pub use super::source::Entity as Source;
pub use super::srs_data::Entity as SrsData;
pub use super::subject::Entity as Subject;
pub use super::tag::Entity as Tag;
