//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "question")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
    pub sync_status: String,
    pub sync_version: i64,
    pub question_type: Option<String>,
    pub source_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub stem: String,
    #[sea_orm(column_type = "Text")]
    pub correct_answer: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub explanation: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub note: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::question_attachment_cross_ref::Entity")]
    QuestionAttachmentCrossRef,
    #[sea_orm(has_many = "super::question_tag_cross_ref::Entity")]
    QuestionTagCrossRef,
    #[sea_orm(
        belongs_to = "super::source::Entity",
        from = "Column::SourceId",
        to = "super::source::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Source,
    #[sea_orm(has_one = "super::srs_data::Entity")]
    SrsData,
}

impl Related<super::question_attachment_cross_ref::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionAttachmentCrossRef.def()
    }
}

impl Related<super::question_tag_cross_ref::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionTagCrossRef.def()
    }
}

impl Related<super::source::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Source.def()
    }
}

impl Related<super::srs_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SrsData.def()
    }
}

impl Related<super::attachment::Entity> for Entity {
    fn to() -> RelationDef {
        super::question_attachment_cross_ref::Relation::Attachment.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::question_attachment_cross_ref::Relation::Question
                .def()
                .rev(),
        )
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::question_tag_cross_ref::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::question_tag_cross_ref::Relation::Question
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
