//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "srs_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub question_id: Uuid,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
    pub sync_status: String,
    pub sync_version: i64,
    #[sea_orm(column_type = "Float")]
    pub stability: f32,
    #[sea_orm(column_type = "Float")]
    pub difficulty: f32,
    pub next_review_at: Option<DateTimeUtc>,
    pub last_reviewed_at: Option<DateTimeUtc>,
    pub review_count: i64,
    pub feedback_history: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::question::Entity",
        from = "Column::QuestionId",
        to = "super::question::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Question,
}

impl Related<super::question::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Question.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
