//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub deleted_at: Option<DateTimeUtc>,
    pub sync_status: String,
    pub sync_version: i64,
    pub name: String,
    pub color: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::question_tag_cross_ref::Entity")]
    QuestionTagCrossRef,
}

impl Related<super::question_tag_cross_ref::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuestionTagCrossRef.def()
    }
}

impl Related<super::question::Entity> for Entity {
    fn to() -> RelationDef {
        super::question_tag_cross_ref::Relation::Question.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::question_tag_cross_ref::Relation::Tag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
